package com.astooltech.advancedview.proteus.value.fontdrawable;

public enum EnumFont {
    fa_heart,//&#xf004;</string>
    fa_star,//&#xf005;</string>
    fa_user,//&#xf007;</string>
    fa_clock,//&#xf017;</string>
    fa_list_alt,//&#xf022;</string>
    fa_flag,//&#xf024;</string>
    fa_bookmark,//&#xf02e;</string>
    fa_image,//&#xf03e;</string>
    fa_edit,//&#xf044;</string>
    fa_times_circle,//&#xf057;</string>
    fa_check_circle,//&#xf058;</string>
    fa_question_circle,//&#xf059;</string>
    fa_eye,//&#xf06e;</string>
    fa_eye_slash,//&#xf070;</string>
    fa_calendar_alt,//&#xf073;</string>
    fa_comment,//&#xf075;</string>
    fa_folder,//&#xf07b;</string>
    fa_folder_open,//&#xf07c;</string>
    fa_chart_bar,//&#xf080;</string>
    fa_comments,//&#xf086;</string>
    fa_star_half,//&#xf089;</string>
    fa_lemon,//&#xf094;</string>
    fa_credit_card,//&#xf09d;</string>
    fa_hdd,//&#xf0a0;</string>
    fa_hand_point_right,//&#xf0a4;</string>
    fa_hand_point_left,//&#xf0a5;</string>
    fa_hand_point_up,//&#xf0a6;</string>
    fa_hand_point_down,//&#xf0a7;</string>
    fa_copy,//&#xf0c5;</string>
    fa_save,//&#xf0c7;</string>
    fa_square,//&#xf0c8;</string>
    fa_envelope,//&#xf0e0;</string>
    fa_lightbulb,//&#xf0eb;</string>
    fa_bell,//&#xf0f3;</string>
    fa_hospital,//&#xf0f8;</string>
    fa_plus_square,//&#xf0fe;</string>
    fa_circle,//&#xf111;</string>
    fa_smile,//&#xf118;</string>
    fa_frown,//&#xf119;</string>
    fa_meh,//&#xf11a;</string>
    fa_keyboard,//&#xf11c;</string>
    fa_calendar,//&#xf133;</string>
    fa_play_circle,//&#xf144;</string>
    fa_minus_square,//&#xf146;</string>
    fa_check_square,//&#xf14a;</string>
    fa_share_square,//&#xf14d;</string>
    fa_compass,//&#xf14e;</string>
    fa_caret_square_down,//&#xf150;</string>
    fa_caret_square_up,//&#xf151;</string>
    fa_caret_square_right,//&#xf152;</string>
    fa_file,//&#xf15b;</string>
    fa_file_alt,//&#xf15c;</string>
    fa_thumbs_up,//&#xf164;</string>
    fa_thumbs_down,//&#xf165;</string>
    fa_sun,//&#xf185;</string>
    fa_moon,//&#xf186;</string>
    fa_caret_square_left,//&#xf191;</string>
    fa_dot_circle,//&#xf192;</string>
    fa_building,//&#xf1ad;</string>
    fa_file_pdf,//&#xf1c1;</string>
    fa_file_word,//&#xf1c2;</string>
    fa_file_excel,//&#xf1c3;</string>
    fa_file_powerpoint,//&#xf1c4;</string>
    fa_file_image,//&#xf1c5;</string>
    fa_file_archive,//&#xf1c6;</string>
    fa_file_audio,//&#xf1c7;</string>
    fa_file_video,//&#xf1c8;</string>
    fa_file_code,//&#xf1c9;</string>
    fa_life_ring,//&#xf1cd;</string>
    fa_paper_plane,//&#xf1d8;</string>
    fa_futbol,//&#xf1e3;</string>
    fa_newspaper,//&#xf1ea;</string>
    fa_bell_slash,//&#xf1f6;</string>
    fa_copyright,//&#xf1f9;</string>
    fa_closed_captioning,//&#xf20a;</string>
    fa_object_group,//&#xf247;</string>
    fa_object_ungroup,//&#xf248;</string>
    fa_sticky_note,//&#xf249;</string>
    fa_clone,//&#xf24d;</string>
    fa_hourglass,//&#xf254;</string>
    fa_hand_rock,//&#xf255;</string>
    fa_hand_paper,//&#xf256;</string>
    fa_hand_scissors,//&#xf257;</string>
    fa_hand_lizard,//&#xf258;</string>
    fa_hand_spock,//&#xf259;</string>
    fa_hand_pointer,//&#xf25a;</string>
    fa_hand_peace,//&#xf25b;</string>
    fa_registered,//&#xf25d;</string>
    fa_calendar_plus,//&#xf271;</string>
    fa_calendar_minus,//&#xf272;</string>
    fa_calendar_times,//&#xf273;</string>
    fa_calendar_check,//&#xf274;</string>
    fa_map,//&#xf279;</string>
    fa_comment_alt,//&#xf27a;</string>
    fa_pause_circle,//&#xf28b;</string>
    fa_stop_circle,//&#xf28d;</string>
    fa_handshake,//&#xf2b5;</string>
    fa_envelope_open,//&#xf2b6;</string>
    fa_address_book,//&#xf2b9;</string>
    fa_address_card,//&#xf2bb;</string>
    fa_user_circle,//&#xf2bd;</string>
    fa_id_badge,//&#xf2c1;</string>
    fa_id_card,//&#xf2c2;</string>
    fa_window_maximize,//&#xf2d0;</string>
    fa_window_minimize,//&#xf2d1;</string>
    fa_window_restore,//&#xf2d2;</string>
    fa_snowflake,//&#xf2dc;</string>
    fa_trash_alt,//&#xf2ed;</string>
    fa_images,//&#xf302;</string>
    fa_clipboard,//&#xf328;</string>
    fa_arrow_alt_circle_down,//&#xf358;</string>
    fa_arrow_alt_circle_left,//&#xf359;</string>
    fa_arrow_alt_circle_right,//&#xf35a;</string>
    fa_arrow_alt_circle_up,//&#xf35b;</string>
    fa_gem,//&#xf3a5;</string>
    fa_money_bill_alt,//&#xf3d1;</string>
    fa_window_close,//&#xf410;</string>
    fa_comment_dots,//&#xf4ad;</string>
    fa_smile_wink,//&#xf4da;</string>
    fa_angry,//&#xf556;</string>
    fa_dizzy,//&#xf567;</string>
    fa_flushed,//&#xf579;</string>
    fa_frown_open,//&#xf57a;</string>
    fa_grimace,//&#xf57f;</string>
    fa_grin,//&#xf580;</string>
    fa_grin_alt,//&#xf581;</string>
    fa_grin_beam,//&#xf582;</string>
    fa_grin_beam_sweat,//&#xf583;</string>
    fa_grin_hearts,//&#xf584;</string>
    fa_grin_squint,//&#xf585;</string>
    fa_grin_squint_tears,//&#xf586;</string>
    fa_grin_stars,//&#xf587;</string>
    fa_grin_tears,//&#xf588;</string>
    fa_grin_tongue,//&#xf589;</string>
    fa_grin_tongue_squint,//&#xf58a;</string>
    fa_grin_tongue_wink,//&#xf58b;</string>
    fa_grin_wink,//&#xf58c;</string>
    fa_kiss,//&#xf596;</string>
    fa_kiss_beam,//&#xf597;</string>
    fa_kiss_wink_heart,//&#xf598;</string>
    fa_laugh,//&#xf599;</string>
    fa_laugh_beam,//&#xf59a;</string>
    fa_laugh_squint,//&#xf59b;</string>
    fa_laugh_wink,//&#xf59c;</string>
    fa_meh_blank,//&#xf5a4;</string>
    fa_meh_rolling_eyes,//&#xf5a5;</string>
    fa_sad_cry,//&#xf5b3;</string>
    fa_sad_tear,//&#xf5b4;</string>
    fa_smile_beam,//&#xf5b8;</string>
    fa_surprise,//&#xf5c2;</string>
    fa_tired,//&#xf5c8;</string>

 
    fa_glass_martini_solid,//&#xf000;</string>
    fa_music_solid,//&#xf001;</string>
    fa_search_solid,//&#xf002;</string>
    fa_heart_solid,//&#xf004;</string>
    fa_star_solid,//&#xf005;</string>
    fa_user_solid,//&#xf007;</string>
    fa_film_solid,//&#xf008;</string>
    fa_th_large_solid,//&#xf009;</string>
    fa_th_solid,//&#xf00a;</string>
    fa_th_list_solid,//&#xf00b;</string>
    fa_check_solid,//&#xf00c;</string>
    fa_times_solid,//&#xf00d;</string>
    fa_search_plus_solid,//&#xf00e;</string>
    fa_search_minus_solid,//&#xf010;</string>
    fa_power_off_solid,//&#xf011;</string>
    fa_signal_solid,//&#xf012;</string>
    fa_cog_solid,//&#xf013;</string>
    fa_home_solid,//&#xf015;</string>
    fa_clock_solid,//&#xf017;</string>
    fa_road_solid,//&#xf018;</string>
    fa_download_solid,//&#xf019;</string>
    fa_inbox_solid,//&#xf01c;</string>
    fa_redo_solid,//&#xf01e;</string>
    fa_sync_solid,//&#xf021;</string>
    fa_list_alt_solid,//&#xf022;</string>
    fa_lock_solid,//&#xf023;</string>
    fa_flag_solid,//&#xf024;</string>
    fa_headphones_solid,//&#xf025;</string>
    fa_volume_off_solid,//&#xf026;</string>
    fa_volume_down_solid,//&#xf027;</string>
    fa_volume_up_solid,//&#xf028;</string>
    fa_qrcode_solid,//&#xf029;</string>
    fa_barcode_solid,//&#xf02a;</string>
    fa_tag_solid,//&#xf02b;</string>
    fa_tags_solid,//&#xf02c;</string>
    fa_book_solid,//&#xf02d;</string>
    fa_bookmark_solid,//&#xf02e;</string>
    fa_print_solid,//&#xf02f;</string>
    fa_camera_solid,//&#xf030;</string>
    fa_font_solid,//&#xf031;</string>
    fa_bold_solid,//&#xf032;</string>
    fa_italic_solid,//&#xf033;</string>
    fa_text_height_solid,//&#xf034;</string>
    fa_text_width_solid,//&#xf035;</string>
    fa_align_left_solid,//&#xf036;</string>
    fa_align_center_solid,//&#xf037;</string>
    fa_align_right_solid,//&#xf038;</string>
    fa_align_justify_solid,//&#xf039;</string>
    fa_list_solid,//&#xf03a;</string>
    fa_outdent_solid,//&#xf03b;</string>
    fa_indent_solid,//&#xf03c;</string>
    fa_video_solid,//&#xf03d;</string>
    fa_image_solid,//&#xf03e;</string>
    fa_map_marker_solid,//&#xf041;</string>
    fa_adjust_solid,//&#xf042;</string>
    fa_tint_solid,//&#xf043;</string>
    fa_edit_solid,//&#xf044;</string>
    fa_step_backward_solid,//&#xf048;</string>
    fa_fast_backward_solid,//&#xf049;</string>
    fa_backward_solid,//&#xf04a;</string>
    fa_play_solid,//&#xf04b;</string>
    fa_pause_solid,//&#xf04c;</string>
    fa_stop_solid,//&#xf04d;</string>
    fa_forward_solid,//&#xf04e;</string>
    fa_fast_forward_solid,//&#xf050;</string>
    fa_step_forward_solid,//&#xf051;</string>
    fa_eject_solid,//&#xf052;</string>
    fa_chevron_left_solid,//&#xf053;</string>
    fa_chevron_right_solid,//&#xf054;</string>
    fa_plus_circle_solid,//&#xf055;</string>
    fa_minus_circle_solid,//&#xf056;</string>
    fa_times_circle_solid,//&#xf057;</string>
    fa_check_circle_solid,//&#xf058;</string>
    fa_question_circle_solid,//&#xf059;</string>
    fa_info_circle_solid,//&#xf05a;</string>
    fa_crosshairs_solid,//&#xf05b;</string>
    fa_ban_solid,//&#xf05e;</string>
    fa_arrow_left_solid,//&#xf060;</string>
    fa_arrow_right_solid,//&#xf061;</string>
    fa_arrow_up_solid,//&#xf062;</string>
    fa_arrow_down_solid,//&#xf063;</string>
    fa_share_solid,//&#xf064;</string>
    fa_expand_solid,//&#xf065;</string>
    fa_compress_solid,//&#xf066;</string>
    fa_plus_solid,//&#xf067;</string>
    fa_minus_solid,//&#xf068;</string>
    fa_asterisk_solid,//&#xf069;</string>
    fa_exclamation_circle_solid,//&#xf06a;</string>
    fa_gift_solid,//&#xf06b;</string>
    fa_leaf_solid,//&#xf06c;</string>
    fa_fire_solid,//&#xf06d;</string>
    fa_eye_solid,//&#xf06e;</string>
    fa_eye_slash_solid,//&#xf070;</string>
    fa_exclamation_triangle_solid,//&#xf071;</string>
    fa_plane_solid,//&#xf072;</string>
    fa_calendar_alt_solid,//&#xf073;</string>
    fa_random_solid,//&#xf074;</string>
    fa_comment_solid,//&#xf075;</string>
    fa_magnet_solid,//&#xf076;</string>
    fa_chevron_up_solid,//&#xf077;</string>
    fa_chevron_down_solid,//&#xf078;</string>
    fa_retweet_solid,//&#xf079;</string>
    fa_shopping_cart_solid,//&#xf07a;</string>
    fa_folder_solid,//&#xf07b;</string>
    fa_folder_open_solid,//&#xf07c;</string>
    fa_chart_bar_solid,//&#xf080;</string>
    fa_camera_retro_solid,//&#xf083;</string>
    fa_key_solid,//&#xf084;</string>
    fa_cogs_solid,//&#xf085;</string>
    fa_comments_solid,//&#xf086;</string>
    fa_star_half_solid,//&#xf089;</string>
    fa_thumbtack_solid,//&#xf08d;</string>
    fa_trophy_solid,//&#xf091;</string>
    fa_upload_solid,//&#xf093;</string>
    fa_lemon_solid,//&#xf094;</string>
    fa_phone_solid,//&#xf095;</string>
    fa_phone_square_solid,//&#xf098;</string>
    fa_unlock_solid,//&#xf09c;</string>
    fa_credit_card_solid,//&#xf09d;</string>
    fa_rss_solid,//&#xf09e;</string>
    fa_hdd_solid,//&#xf0a0;</string>
    fa_bullhorn_solid,//&#xf0a1;</string>
    fa_certificate_solid,//&#xf0a3;</string>
    fa_hand_point_right_solid,//&#xf0a4;</string>
    fa_hand_point_left_solid,//&#xf0a5;</string>
    fa_hand_point_up_solid,//&#xf0a6;</string>
    fa_hand_point_down_solid,//&#xf0a7;</string>
    fa_arrow_circle_left_solid,//&#xf0a8;</string>
    fa_arrow_circle_right_solid,//&#xf0a9;</string>
    fa_arrow_circle_up_solid,//&#xf0aa;</string>
    fa_arrow_circle_down_solid,//&#xf0ab;</string>
    fa_globe_solid,//&#xf0ac;</string>
    fa_wrench_solid,//&#xf0ad;</string>
    fa_tasks_solid,//&#xf0ae;</string>
    fa_filter_solid,//&#xf0b0;</string>
    fa_briefcase_solid,//&#xf0b1;</string>
    fa_arrows_alt_solid,//&#xf0b2;</string>
    fa_users_solid,//&#xf0c0;</string>
    fa_link_solid,//&#xf0c1;</string>
    fa_cloud_solid,//&#xf0c2;</string>
    fa_flask_solid,//&#xf0c3;</string>
    fa_cut_solid,//&#xf0c4;</string>
    fa_copy_solid,//&#xf0c5;</string>
    fa_paperclip_solid,//&#xf0c6;</string>
    fa_save_solid,//&#xf0c7;</string>
    fa_square_solid,//&#xf0c8;</string>
    fa_bars_solid,//&#xf0c9;</string>
    fa_list_ul_solid,//&#xf0ca;</string>
    fa_list_ol_solid,//&#xf0cb;</string>
    fa_strikethrough_solid,//&#xf0cc;</string>
    fa_underline_solid,//&#xf0cd;</string>
    fa_table_solid,//&#xf0ce;</string>
    fa_magic_solid,//&#xf0d0;</string>
    fa_truck_solid,//&#xf0d1;</string>
    fa_money_bill_solid,//&#xf0d6;</string>
    fa_caret_down_solid,//&#xf0d7;</string>
    fa_caret_up_solid,//&#xf0d8;</string>
    fa_caret_left_solid,//&#xf0d9;</string>
    fa_caret_right_solid,//&#xf0da;</string>
    fa_columns_solid,//&#xf0db;</string>
    fa_sort_solid,//&#xf0dc;</string>
    fa_sort_down_solid,//&#xf0dd;</string>
    fa_sort_up_solid,//&#xf0de;</string>
    fa_envelope_solid,//&#xf0e0;</string>
    fa_undo_solid,//&#xf0e2;</string>
    fa_gavel_solid,//&#xf0e3;</string>
    fa_bolt_solid,//&#xf0e7;</string>
    fa_sitemap_solid,//&#xf0e8;</string>
    fa_umbrella_solid,//&#xf0e9;</string>
    fa_paste_solid,//&#xf0ea;</string>
    fa_lightbulb_solid,//&#xf0eb;</string>
    fa_user_md_solid,//&#xf0f0;</string>
    fa_stethoscope_solid,//&#xf0f1;</string>
    fa_suitcase_solid,//&#xf0f2;</string>
    fa_bell_solid,//&#xf0f3;</string>
    fa_coffee_solid,//&#xf0f4;</string>
    fa_hospital_solid,//&#xf0f8;</string>
    fa_ambulance_solid,//&#xf0f9;</string>
    fa_medkit_solid,//&#xf0fa;</string>
    fa_fighter_jet_solid,//&#xf0fb;</string>
    fa_beer_solid,//&#xf0fc;</string>
    fa_h_square_solid,//&#xf0fd;</string>
    fa_plus_square_solid,//&#xf0fe;</string>
    fa_angle_double_left_solid,//&#xf100;</string>
    fa_angle_double_right_solid,//&#xf101;</string>
    fa_angle_double_up_solid,//&#xf102;</string>
    fa_angle_double_down_solid,//&#xf103;</string>
    fa_angle_left_solid,//&#xf104;</string>
    fa_angle_right_solid,//&#xf105;</string>
    fa_angle_up_solid,//&#xf106;</string>
    fa_angle_down_solid,//&#xf107;</string>
    fa_desktop_solid,//&#xf108;</string>
    fa_laptop_solid,//&#xf109;</string>
    fa_tablet_solid,//&#xf10a;</string>
    fa_mobile_solid,//&#xf10b;</string>
    fa_quote_left_solid,//&#xf10d;</string>
    fa_quote_right_solid,//&#xf10e;</string>
    fa_spinner_solid,//&#xf110;</string>
    fa_circle_solid,//&#xf111;</string>
    fa_smile_solid,//&#xf118;</string>
    fa_frown_solid,//&#xf119;</string>
    fa_meh_solid,//&#xf11a;</string>
    fa_gamepad_solid,//&#xf11b;</string>
    fa_keyboard_solid,//&#xf11c;</string>
    fa_flag_checkered_solid,//&#xf11e;</string>
    fa_terminal_solid,//&#xf120;</string>
    fa_code_solid,//&#xf121;</string>
    fa_reply_all_solid,//&#xf122;</string>
    fa_location_arrow_solid,//&#xf124;</string>
    fa_crop_solid,//&#xf125;</string>
    fa_code_branch_solid,//&#xf126;</string>
    fa_unlink_solid,//&#xf127;</string>
    fa_question_solid,//&#xf128;</string>
    fa_info_solid,//&#xf129;</string>
    fa_exclamation_solid,//&#xf12a;</string>
    fa_superscript_solid,//&#xf12b;</string>
    fa_subscript_solid,//&#xf12c;</string>
    fa_eraser_solid,//&#xf12d;</string>
    fa_puzzle_piece_solid,//&#xf12e;</string>
    fa_microphone_solid,//&#xf130;</string>
    fa_microphone_slash_solid,//&#xf131;</string>
    fa_calendar_solid,//&#xf133;</string>
    fa_fire_extinguisher_solid,//&#xf134;</string>
    fa_rocket_solid,//&#xf135;</string>
    fa_chevron_circle_left_solid,//&#xf137;</string>
    fa_chevron_circle_right_solid,//&#xf138;</string>
    fa_chevron_circle_up_solid,//&#xf139;</string>
    fa_chevron_circle_down_solid,//&#xf13a;</string>
    fa_anchor_solid,//&#xf13d;</string>
    fa_unlock_alt_solid,//&#xf13e;</string>
    fa_bullseye_solid,//&#xf140;</string>
    fa_ellipsis_h_solid,//&#xf141;</string>
    fa_ellipsis_v_solid,//&#xf142;</string>
    fa_rss_square_solid,//&#xf143;</string>
    fa_play_circle_solid,//&#xf144;</string>
    fa_minus_square_solid,//&#xf146;</string>
    fa_check_square_solid,//&#xf14a;</string>
    fa_pen_square_solid,//&#xf14b;</string>
    fa_share_square_solid,//&#xf14d;</string>
    fa_compass_solid,//&#xf14e;</string>
    fa_caret_square_down_solid,//&#xf150;</string>
    fa_caret_square_up_solid,//&#xf151;</string>
    fa_caret_square_right_solid,//&#xf152;</string>
    fa_euro_sign_solid,//&#xf153;</string>
    fa_pound_sign_solid,//&#xf154;</string>
    fa_dollar_sign_solid,//&#xf155;</string>
    fa_rupee_sign_solid,//&#xf156;</string>
    fa_yen_sign_solid,//&#xf157;</string>
    fa_ruble_sign_solid,//&#xf158;</string>
    fa_won_sign_solid,//&#xf159;</string>
    fa_file_solid,//&#xf15b;</string>
    fa_file_alt_solid,//&#xf15c;</string>
    fa_sort_alpha_down_solid,//&#xf15d;</string>
    fa_sort_alpha_up_solid,//&#xf15e;</string>
    fa_sort_amount_down_solid,//&#xf160;</string>
    fa_sort_amount_up_solid,//&#xf161;</string>
    fa_sort_numeric_down_solid,//&#xf162;</string>
    fa_sort_numeric_up_solid,//&#xf163;</string>
    fa_thumbs_up_solid,//&#xf164;</string>
    fa_thumbs_down_solid,//&#xf165;</string>
    fa_female_solid,//&#xf182;</string>
    fa_male_solid,//&#xf183;</string>
    fa_sun_solid,//&#xf185;</string>
    fa_moon_solid,//&#xf186;</string>
    fa_archive_solid,//&#xf187;</string>
    fa_bug_solid,//&#xf188;</string>
    fa_caret_square_left_solid,//&#xf191;</string>
    fa_dot_circle_solid,//&#xf192;</string>
    fa_wheelchair_solid,//&#xf193;</string>
    fa_lira_sign_solid,//&#xf195;</string>
    fa_space_shuttle_solid,//&#xf197;</string>
    fa_envelope_square_solid,//&#xf199;</string>
    fa_university_solid,//&#xf19c;</string>
    fa_graduation_cap_solid,//&#xf19d;</string>
    fa_language_solid,//&#xf1ab;</string>
    fa_fax_solid,//&#xf1ac;</string>
    fa_building_solid,//&#xf1ad;</string>
    fa_child_solid,//&#xf1ae;</string>
    fa_paw_solid,//&#xf1b0;</string>
    fa_cube_solid,//&#xf1b2;</string>
    fa_cubes_solid,//&#xf1b3;</string>
    fa_recycle_solid,//&#xf1b8;</string>
    fa_car_solid,//&#xf1b9;</string>
    fa_taxi_solid,//&#xf1ba;</string>
    fa_tree_solid,//&#xf1bb;</string>
    fa_database_solid,//&#xf1c0;</string>
    fa_file_pdf_solid,//&#xf1c1;</string>
    fa_file_word_solid,//&#xf1c2;</string>
    fa_file_excel_solid,//&#xf1c3;</string>
    fa_file_powerpoint_solid,//&#xf1c4;</string>
    fa_file_image_solid,//&#xf1c5;</string>
    fa_file_archive_solid,//&#xf1c6;</string>
    fa_file_audio_solid,//&#xf1c7;</string>
    fa_file_video_solid,//&#xf1c8;</string>
    fa_file_code_solid,//&#xf1c9;</string>
    fa_life_ring_solid,//&#xf1cd;</string>
    fa_circle_notch_solid,//&#xf1ce;</string>
    fa_paper_plane_solid,//&#xf1d8;</string>
    fa_history_solid,//&#xf1da;</string>
    fa_heading_solid,//&#xf1dc;</string>
    fa_paragraph_solid,//&#xf1dd;</string>
    fa_sliders_h_solid,//&#xf1de;</string>
    fa_share_alt_solid,//&#xf1e0;</string>
    fa_share_alt_square_solid,//&#xf1e1;</string>
    fa_bomb_solid,//&#xf1e2;</string>
    fa_futbol_solid,//&#xf1e3;</string>
    fa_tty_solid,//&#xf1e4;</string>
    fa_binoculars_solid,//&#xf1e5;</string>
    fa_plug_solid,//&#xf1e6;</string>
    fa_newspaper_solid,//&#xf1ea;</string>
    fa_wifi_solid,//&#xf1eb;</string>
    fa_calculator_solid,//&#xf1ec;</string>
    fa_bell_slash_solid,//&#xf1f6;</string>
    fa_trash_solid,//&#xf1f8;</string>
    fa_copyright_solid,//&#xf1f9;</string>
    fa_at_solid,//&#xf1fa;</string>
    fa_eye_dropper_solid,//&#xf1fb;</string>
    fa_paint_brush_solid,//&#xf1fc;</string>
    fa_birthday_cake_solid,//&#xf1fd;</string>
    fa_chart_area_solid,//&#xf1fe;</string>
    fa_chart_pie_solid,//&#xf200;</string>
    fa_chart_line_solid,//&#xf201;</string>
    fa_toggle_off_solid,//&#xf204;</string>
    fa_toggle_on_solid,//&#xf205;</string>
    fa_bicycle_solid,//&#xf206;</string>
    fa_bus_solid,//&#xf207;</string>
    fa_closed_captioning_solid,//&#xf20a;</string>
    fa_shekel_sign_solid,//&#xf20b;</string>
    fa_cart_plus_solid,//&#xf217;</string>
    fa_cart_arrow_down_solid,//&#xf218;</string>
    fa_ship_solid,//&#xf21a;</string>
    fa_user_secret_solid,//&#xf21b;</string>
    fa_motorcycle_solid,//&#xf21c;</string>
    fa_street_view_solid,//&#xf21d;</string>
    fa_heartbeat_solid,//&#xf21e;</string>
    fa_venus_solid,//&#xf221;</string>
    fa_mars_solid,//&#xf222;</string>
    fa_mercury_solid,//&#xf223;</string>
    fa_transgender_solid,//&#xf224;</string>
    fa_transgender_alt_solid,//&#xf225;</string>
    fa_venus_double_solid,//&#xf226;</string>
    fa_mars_double_solid,//&#xf227;</string>
    fa_venus_mars_solid,//&#xf228;</string>
    fa_mars_stroke_solid,//&#xf229;</string>
    fa_mars_stroke_v_solid,//&#xf22a;</string>
    fa_mars_stroke_h_solid,//&#xf22b;</string>
    fa_neuter_solid,//&#xf22c;</string>
    fa_genderless_solid,//&#xf22d;</string>
    fa_server_solid,//&#xf233;</string>
    fa_user_plus_solid,//&#xf234;</string>
    fa_user_times_solid,//&#xf235;</string>
    fa_bed_solid,//&#xf236;</string>
    fa_train_solid,//&#xf238;</string>
    fa_subway_solid,//&#xf239;</string>
    fa_battery_full_solid,//&#xf240;</string>
    fa_battery_three_quarters_solid,//&#xf241;</string>
    fa_battery_half_solid,//&#xf242;</string>
    fa_battery_quarter_solid,//&#xf243;</string>
    fa_battery_empty_solid,//&#xf244;</string>
    fa_mouse_pointer_solid,//&#xf245;</string>
    fa_i_cursor_solid,//&#xf246;</string>
    fa_object_group_solid,//&#xf247;</string>
    fa_object_ungroup_solid,//&#xf248;</string>
    fa_sticky_note_solid,//&#xf249;</string>
    fa_clone_solid,//&#xf24d;</string>
    fa_balance_scale_solid,//&#xf24e;</string>
    fa_hourglass_start_solid,//&#xf251;</string>
    fa_hourglass_half_solid,//&#xf252;</string>
    fa_hourglass_end_solid,//&#xf253;</string>
    fa_hourglass_solid,//&#xf254;</string>
    fa_hand_rock_solid,//&#xf255;</string>
    fa_hand_paper_solid,//&#xf256;</string>
    fa_hand_scissors_solid,//&#xf257;</string>
    fa_hand_lizard_solid,//&#xf258;</string>
    fa_hand_spock_solid,//&#xf259;</string>
    fa_hand_pointer_solid,//&#xf25a;</string>
    fa_hand_peace_solid,//&#xf25b;</string>
    fa_trademark_solid,//&#xf25c;</string>
    fa_registered_solid,//&#xf25d;</string>
    fa_tv_solid,//&#xf26c;</string>
    fa_calendar_plus_solid,//&#xf271;</string>
    fa_calendar_minus_solid,//&#xf272;</string>
    fa_calendar_times_solid,//&#xf273;</string>
    fa_calendar_check_solid,//&#xf274;</string>
    fa_industry_solid,//&#xf275;</string>
    fa_map_pin_solid,//&#xf276;</string>
    fa_map_signs_solid,//&#xf277;</string>
    fa_map_solid,//&#xf279;</string>
    fa_comment_alt_solid,//&#xf27a;</string>
    fa_pause_circle_solid,//&#xf28b;</string>
    fa_stop_circle_solid,//&#xf28d;</string>
    fa_shopping_bag_solid,//&#xf290;</string>
    fa_shopping_basket_solid,//&#xf291;</string>
    fa_hashtag_solid,//&#xf292;</string>
    fa_percent_solid,//&#xf295;</string>
    fa_universal_access_solid,//&#xf29a;</string>
    fa_blind_solid,//&#xf29d;</string>
    fa_audio_description_solid,//&#xf29e;</string>
    fa_phone_volume_solid,//&#xf2a0;</string>
    fa_braille_solid,//&#xf2a1;</string>
    fa_assistive_listening_systems_solid,//&#xf2a2;</string>
    fa_american_sign_language_interpreting_solid,//&#xf2a3;</string>
    fa_deaf_solid,//&#xf2a4;</string>
    fa_sign_language_solid,//&#xf2a7;</string>
    fa_low_vision_solid,//&#xf2a8;</string>
    fa_handshake_solid,//&#xf2b5;</string>
    fa_envelope_open_solid,//&#xf2b6;</string>
    fa_address_book_solid,//&#xf2b9;</string>
    fa_address_card_solid,//&#xf2bb;</string>
    fa_user_circle_solid,//&#xf2bd;</string>
    fa_id_badge_solid,//&#xf2c1;</string>
    fa_id_card_solid,//&#xf2c2;</string>
    fa_thermometer_full_solid,//&#xf2c7;</string>
    fa_thermometer_three_quarters_solid,//&#xf2c8;</string>
    fa_thermometer_half_solid,//&#xf2c9;</string>
    fa_thermometer_quarter_solid,//&#xf2ca;</string>
    fa_thermometer_empty_solid,//&#xf2cb;</string>
    fa_shower_solid,//&#xf2cc;</string>
    fa_bath_solid,//&#xf2cd;</string>
    fa_podcast_solid,//&#xf2ce;</string>
    fa_window_maximize_solid,//&#xf2d0;</string>
    fa_window_minimize_solid,//&#xf2d1;</string>
    fa_window_restore_solid,//&#xf2d2;</string>
    fa_microchip_solid,//&#xf2db;</string>
    fa_snowflake_solid,//&#xf2dc;</string>
    fa_utensil_spoon_solid,//&#xf2e5;</string>
    fa_utensils_solid,//&#xf2e7;</string>
    fa_undo_alt_solid,//&#xf2ea;</string>
    fa_trash_alt_solid,//&#xf2ed;</string>
    fa_sync_alt_solid,//&#xf2f1;</string>
    fa_stopwatch_solid,//&#xf2f2;</string>
    fa_sign_out_alt_solid,//&#xf2f5;</string>
    fa_sign_in_alt_solid,//&#xf2f6;</string>
    fa_redo_alt_solid,//&#xf2f9;</string>
    fa_poo_solid,//&#xf2fe;</string>
    fa_images_solid,//&#xf302;</string>
    fa_pencil_alt_solid,//&#xf303;</string>
    fa_pen_solid,//&#xf304;</string>
    fa_pen_alt_solid,//&#xf305;</string>
    fa_long_arrow_alt_down_solid,//&#xf309;</string>
    fa_long_arrow_alt_left_solid,//&#xf30a;</string>
    fa_long_arrow_alt_right_solid,//&#xf30b;</string>
    fa_long_arrow_alt_up_solid,//&#xf30c;</string>
    fa_expand_arrows_alt_solid,//&#xf31e;</string>
    fa_clipboard_solid,//&#xf328;</string>
    fa_arrows_alt_h_solid,//&#xf337;</string>
    fa_arrows_alt_v_solid,//&#xf338;</string>
    fa_arrow_alt_circle_down_solid,//&#xf358;</string>
    fa_arrow_alt_circle_left_solid,//&#xf359;</string>
    fa_arrow_alt_circle_right_solid,//&#xf35a;</string>
    fa_arrow_alt_circle_up_solid,//&#xf35b;</string>
    fa_external_link_alt_solid,//&#xf35d;</string>
    fa_external_link_square_alt_solid,//&#xf360;</string>
    fa_exchange_alt_solid,//&#xf362;</string>
    fa_cloud_download_alt_solid,//&#xf381;</string>
    fa_cloud_upload_alt_solid,//&#xf382;</string>
    fa_gem_solid,//&#xf3a5;</string>
    fa_level_down_alt_solid,//&#xf3be;</string>
    fa_level_up_alt_solid,//&#xf3bf;</string>
    fa_lock_open_solid,//&#xf3c1;</string>
    fa_map_marker_alt_solid,//&#xf3c5;</string>
    fa_microphone_alt_solid,//&#xf3c9;</string>
    fa_mobile_alt_solid,//&#xf3cd;</string>
    fa_money_bill_alt_solid,//&#xf3d1;</string>
    fa_phone_slash_solid,//&#xf3dd;</string>
    fa_portrait_solid,//&#xf3e0;</string>
    fa_reply_solid,//&#xf3e5;</string>
    fa_shield_alt_solid,//&#xf3ed;</string>
    fa_tablet_alt_solid,//&#xf3fa;</string>
    fa_tachometer_alt_solid,//&#xf3fd;</string>
    fa_ticket_alt_solid,//&#xf3ff;</string>
    fa_user_alt_solid,//&#xf406;</string>
    fa_window_close_solid,//&#xf410;</string>
    fa_baseball_ball_solid,//&#xf433;</string>
    fa_basketball_ball_solid,//&#xf434;</string>
    fa_bowling_ball_solid,//&#xf436;</string>
    fa_chess_solid,//&#xf439;</string>
    fa_chess_bishop_solid,//&#xf43a;</string>
    fa_chess_board_solid,//&#xf43c;</string>
    fa_chess_king_solid,//&#xf43f;</string>
    fa_chess_knight_solid,//&#xf441;</string>
    fa_chess_pawn_solid,//&#xf443;</string>
    fa_chess_queen_solid,//&#xf445;</string>
    fa_chess_rook_solid,//&#xf447;</string>
    fa_dumbbell_solid,//&#xf44b;</string>
    fa_football_ball_solid,//&#xf44e;</string>
    fa_golf_ball_solid,//&#xf450;</string>
    fa_hockey_puck_solid,//&#xf453;</string>
    fa_quidditch_solid,//&#xf458;</string>
    fa_square_full_solid,//&#xf45c;</string>
    fa_table_tennis_solid,//&#xf45d;</string>
    fa_volleyball_ball_solid,//&#xf45f;</string>
    fa_allergies_solid,//&#xf461;</string>
    fa_band_aid_solid,//&#xf462;</string>
    fa_box_solid,//&#xf466;</string>
    fa_boxes_solid,//&#xf468;</string>
    fa_briefcase_medical_solid,//&#xf469;</string>
    fa_burn_solid,//&#xf46a;</string>
    fa_capsules_solid,//&#xf46b;</string>
    fa_clipboard_check_solid,//&#xf46c;</string>
    fa_clipboard_list_solid,//&#xf46d;</string>
    fa_diagnoses_solid,//&#xf470;</string>
    fa_dna_solid,//&#xf471;</string>
    fa_dolly_solid,//&#xf472;</string>
    fa_dolly_flatbed_solid,//&#xf474;</string>
    fa_file_medical_solid,//&#xf477;</string>
    fa_file_medical_alt_solid,//&#xf478;</string>
    fa_first_aid_solid,//&#xf479;</string>
    fa_hospital_alt_solid,//&#xf47d;</string>
    fa_hospital_symbol_solid,//&#xf47e;</string>
    fa_id_card_alt_solid,//&#xf47f;</string>
    fa_notes_medical_solid,//&#xf481;</string>
    fa_pallet_solid,//&#xf482;</string>
    fa_pills_solid,//&#xf484;</string>
    fa_prescription_bottle_solid,//&#xf485;</string>
    fa_prescription_bottle_alt_solid,//&#xf486;</string>
    fa_procedures_solid,//&#xf487;</string>
    fa_shipping_fast_solid,//&#xf48b;</string>
    fa_smoking_solid,//&#xf48d;</string>
    fa_syringe_solid,//&#xf48e;</string>
    fa_tablets_solid,//&#xf490;</string>
    fa_thermometer_solid,//&#xf491;</string>
    fa_vial_solid,//&#xf492;</string>
    fa_vials_solid,//&#xf493;</string>
    fa_warehouse_solid,//&#xf494;</string>
    fa_weight_solid,//&#xf496;</string>
    fa_x_ray_solid,//&#xf497;</string>
    fa_box_open_solid,//&#xf49e;</string>
    fa_comment_dots_solid,//&#xf4ad;</string>
    fa_comment_slash_solid,//&#xf4b3;</string>
    fa_couch_solid,//&#xf4b8;</string>
    fa_donate_solid,//&#xf4b9;</string>
    fa_dove_solid,//&#xf4ba;</string>
    fa_hand_holding_solid,//&#xf4bd;</string>
    fa_hand_holding_heart_solid,//&#xf4be;</string>
    fa_hand_holding_usd_solid,//&#xf4c0;</string>
    fa_hands_solid,//&#xf4c2;</string>
    fa_hands_helping_solid,//&#xf4c4;</string>
    fa_parachute_box_solid,//&#xf4cd;</string>
    fa_people_carry_solid,//&#xf4ce;</string>
    fa_piggy_bank_solid,//&#xf4d3;</string>
    fa_ribbon_solid,//&#xf4d6;</string>
    fa_route_solid,//&#xf4d7;</string>
    fa_seedling_solid,//&#xf4d8;</string>
    fa_sign_solid,//&#xf4d9;</string>
    fa_smile_wink_solid,//&#xf4da;</string>
    fa_tape_solid,//&#xf4db;</string>
    fa_truck_loading_solid,//&#xf4de;</string>
    fa_truck_moving_solid,//&#xf4df;</string>
    fa_video_slash_solid,//&#xf4e2;</string>
    fa_wine_glass_solid,//&#xf4e3;</string>
    fa_user_alt_slash_solid,//&#xf4fa;</string>
    fa_user_astronaut_solid,//&#xf4fb;</string>
    fa_user_check_solid,//&#xf4fc;</string>
    fa_user_clock_solid,//&#xf4fd;</string>
    fa_user_cog_solid,//&#xf4fe;</string>
    fa_user_edit_solid,//&#xf4ff;</string>
    fa_user_friends_solid,//&#xf500;</string>
    fa_user_graduate_solid,//&#xf501;</string>
    fa_user_lock_solid,//&#xf502;</string>
    fa_user_minus_solid,//&#xf503;</string>
    fa_user_ninja_solid,//&#xf504;</string>
    fa_user_shield_solid,//&#xf505;</string>
    fa_user_slash_solid,//&#xf506;</string>
    fa_user_tag_solid,//&#xf507;</string>
    fa_user_tie_solid,//&#xf508;</string>
    fa_users_cog_solid,//&#xf509;</string>
    fa_blender_solid,//&#xf517;</string>
    fa_book_open_solid,//&#xf518;</string>
    fa_broadcast_tower_solid,//&#xf519;</string>
    fa_broom_solid,//&#xf51a;</string>
    fa_chalkboard_solid,//&#xf51b;</string>
    fa_chalkboard_teacher_solid,//&#xf51c;</string>
    fa_church_solid,//&#xf51d;</string>
    fa_coins_solid,//&#xf51e;</string>
    fa_compact_disc_solid,//&#xf51f;</string>
    fa_crow_solid,//&#xf520;</string>
    fa_crown_solid,//&#xf521;</string>
    fa_dice_solid,//&#xf522;</string>
    fa_dice_five_solid,//&#xf523;</string>
    fa_dice_four_solid,//&#xf524;</string>
    fa_dice_one_solid,//&#xf525;</string>
    fa_dice_six_solid,//&#xf526;</string>
    fa_dice_three_solid,//&#xf527;</string>
    fa_dice_two_solid,//&#xf528;</string>
    fa_divide_solid,//&#xf529;</string>
    fa_door_closed_solid,//&#xf52a;</string>
    fa_door_open_solid,//&#xf52b;</string>
    fa_equals_solid,//&#xf52c;</string>
    fa_feather_solid,//&#xf52d;</string>
    fa_frog_solid,//&#xf52e;</string>
    fa_gas_pump_solid,//&#xf52f;</string>
    fa_glasses_solid,//&#xf530;</string>
    fa_greater_than_solid,//&#xf531;</string>
    fa_greater_than_equal_solid,//&#xf532;</string>
    fa_helicopter_solid,//&#xf533;</string>
    fa_infinity_solid,//&#xf534;</string>
    fa_kiwi_bird_solid,//&#xf535;</string>
    fa_less_than_solid,//&#xf536;</string>
    fa_less_than_equal_solid,//&#xf537;</string>
    fa_memory_solid,//&#xf538;</string>
    fa_microphone_alt_slash_solid,//&#xf539;</string>
    fa_money_bill_wave_solid,//&#xf53a;</string>
    fa_money_bill_wave_alt_solid,//&#xf53b;</string>
    fa_money_check_solid,//&#xf53c;</string>
    fa_money_check_alt_solid,//&#xf53d;</string>
    fa_not_equal_solid,//&#xf53e;</string>
    fa_palette_solid,//&#xf53f;</string>
    fa_parking_solid,//&#xf540;</string>
    fa_percentage_solid,//&#xf541;</string>
    fa_project_diagram_solid,//&#xf542;</string>
    fa_receipt_solid,//&#xf543;</string>
    fa_robot_solid,//&#xf544;</string>
    fa_ruler_solid,//&#xf545;</string>
    fa_ruler_combined_solid,//&#xf546;</string>
    fa_ruler_horizontal_solid,//&#xf547;</string>
    fa_ruler_vertical_solid,//&#xf548;</string>
    fa_school_solid,//&#xf549;</string>
    fa_screwdriver_solid,//&#xf54a;</string>
    fa_shoe_prints_solid,//&#xf54b;</string>
    fa_skull_solid,//&#xf54c;</string>
    fa_smoking_ban_solid,//&#xf54d;</string>
    fa_store_solid,//&#xf54e;</string>
    fa_store_alt_solid,//&#xf54f;</string>
    fa_stream_solid,//&#xf550;</string>
    fa_stroopwafel_solid,//&#xf551;</string>
    fa_toolbox_solid,//&#xf552;</string>
    fa_tshirt_solid,//&#xf553;</string>
    fa_walking_solid,//&#xf554;</string>
    fa_wallet_solid,//&#xf555;</string>
    fa_angry_solid,//&#xf556;</string>
    fa_archway_solid,//&#xf557;</string>
    fa_atlas_solid,//&#xf558;</string>
    fa_award_solid,//&#xf559;</string>
    fa_backspace_solid,//&#xf55a;</string>
    fa_bezier_curve_solid,//&#xf55b;</string>
    fa_bong_solid,//&#xf55c;</string>
    fa_brush_solid,//&#xf55d;</string>
    fa_bus_alt_solid,//&#xf55e;</string>
    fa_cannabis_solid,//&#xf55f;</string>
    fa_check_double_solid,//&#xf560;</string>
    fa_cocktail_solid,//&#xf561;</string>
    fa_concierge_bell_solid,//&#xf562;</string>
    fa_cookie_solid,//&#xf563;</string>
    fa_cookie_bite_solid,//&#xf564;</string>
    fa_crop_alt_solid,//&#xf565;</string>
    fa_digital_tachograph_solid,//&#xf566;</string>
    fa_dizzy_solid,//&#xf567;</string>
    fa_drafting_compass_solid,//&#xf568;</string>
    fa_drum_solid,//&#xf569;</string>
    fa_drum_steelpan_solid,//&#xf56a;</string>
    fa_feather_alt_solid,//&#xf56b;</string>
    fa_file_contract_solid,//&#xf56c;</string>
    fa_file_download_solid,//&#xf56d;</string>
    fa_file_export_solid,//&#xf56e;</string>
    fa_file_import_solid,//&#xf56f;</string>
    fa_file_invoice_solid,//&#xf570;</string>
    fa_file_invoice_dollar_solid,//&#xf571;</string>
    fa_file_prescription_solid,//&#xf572;</string>
    fa_file_signature_solid,//&#xf573;</string>
    fa_file_upload_solid,//&#xf574;</string>
    fa_fill_solid,//&#xf575;</string>
    fa_fill_drip_solid,//&#xf576;</string>
    fa_fingerprint_solid,//&#xf577;</string>
    fa_fish_solid,//&#xf578;</string>
    fa_flushed_solid,//&#xf579;</string>
    fa_frown_open_solid,//&#xf57a;</string>
    fa_glass_martini_alt_solid,//&#xf57b;</string>
    fa_globe_africa_solid,//&#xf57c;</string>
    fa_globe_americas_solid,//&#xf57d;</string>
    fa_globe_asia_solid,//&#xf57e;</string>
    fa_grimace_solid,//&#xf57f;</string>
    fa_grin_solid,//&#xf580;</string>
    fa_grin_alt_solid,//&#xf581;</string>
    fa_grin_beam_solid,//&#xf582;</string>
    fa_grin_beam_sweat_solid,//&#xf583;</string>
    fa_grin_hearts_solid,//&#xf584;</string>
    fa_grin_squint_solid,//&#xf585;</string>
    fa_grin_squint_tears_solid,//&#xf586;</string>
    fa_grin_stars_solid,//&#xf587;</string>
    fa_grin_tears_solid,//&#xf588;</string>
    fa_grin_tongue_solid,//&#xf589;</string>
    fa_grin_tongue_squint_solid,//&#xf58a;</string>
    fa_grin_tongue_wink_solid,//&#xf58b;</string>
    fa_grin_wink_solid,//&#xf58c;</string>
    fa_grip_horizontal_solid,//&#xf58d;</string>
    fa_grip_vertical_solid,//&#xf58e;</string>
    fa_headphones_alt_solid,//&#xf58f;</string>
    fa_headset_solid,//&#xf590;</string>
    fa_highlighter_solid,//&#xf591;</string>
    fa_hot_tub_solid,//&#xf593;</string>
    fa_hotel_solid,//&#xf594;</string>
    fa_joint_solid,//&#xf595;</string>
    fa_kiss_solid,//&#xf596;</string>
    fa_kiss_beam_solid,//&#xf597;</string>
    fa_kiss_wink_heart_solid,//&#xf598;</string>
    fa_laugh_solid,//&#xf599;</string>
    fa_laugh_beam_solid,//&#xf59a;</string>
    fa_laugh_squint_solid,//&#xf59b;</string>
    fa_laugh_wink_solid,//&#xf59c;</string>
    fa_luggage_cart_solid,//&#xf59d;</string>
    fa_map_marked_solid,//&#xf59f;</string>
    fa_map_marked_alt_solid,//&#xf5a0;</string>
    fa_marker_solid,//&#xf5a1;</string>
    fa_medal_solid,//&#xf5a2;</string>
    fa_meh_blank_solid,//&#xf5a4;</string>
    fa_meh_rolling_eyes_solid,//&#xf5a5;</string>
    fa_monument_solid,//&#xf5a6;</string>
    fa_mortar_pestle_solid,//&#xf5a7;</string>
    fa_paint_roller_solid,//&#xf5aa;</string>
    fa_passport_solid,//&#xf5ab;</string>
    fa_pen_fancy_solid,//&#xf5ac;</string>
    fa_pen_nib_solid,//&#xf5ad;</string>
    fa_pencil_ruler_solid,//&#xf5ae;</string>
    fa_plane_arrival_solid,//&#xf5af;</string>
    fa_plane_departure_solid,//&#xf5b0;</string>
    fa_prescription_solid,//&#xf5b1;</string>
    fa_sad_cry_solid,//&#xf5b3;</string>
    fa_sad_tear_solid,//&#xf5b4;</string>
    fa_shuttle_van_solid,//&#xf5b6;</string>
    fa_signature_solid,//&#xf5b7;</string>
    fa_smile_beam_solid,//&#xf5b8;</string>
    fa_solar_panel_solid,//&#xf5ba;</string>
    fa_spa_solid,//&#xf5bb;</string>
    fa_splotch_solid,//&#xf5bc;</string>
    fa_spray_can_solid,//&#xf5bd;</string>
    fa_stamp_solid,//&#xf5bf;</string>
    fa_star_half_alt_solid,//&#xf5c0;</string>
    fa_suitcase_rolling_solid,//&#xf5c1;</string>
    fa_surprise_solid,//&#xf5c2;</string>
    fa_swatchbook_solid,//&#xf5c3;</string>
    fa_swimmer_solid,//&#xf5c4;</string>
    fa_swimming_pool_solid,//&#xf5c5;</string>
    fa_tint_slash_solid,//&#xf5c7;</string>
    fa_tired_solid,//&#xf5c8;</string>
    fa_tooth_solid,//&#xf5c9;</string>
    fa_umbrella_beach_solid,//&#xf5ca;</string>
    fa_vector_square_solid,//&#xf5cb;</string>
    fa_weight_hanging_solid,//&#xf5cd;</string>
    fa_wine_glass_alt_solid,//&#xf5ce;</string>
    fa_air_freshener_solid,//&#xf5d0;</string>
    fa_apple_alt_solid,//&#xf5d1;</string>
    fa_atom_solid,//&#xf5d2;</string>
    fa_bone_solid,//&#xf5d7;</string>
    fa_book_reader_solid,//&#xf5da;</string>
    fa_brain_solid,//&#xf5dc;</string>
    fa_car_alt_solid,//&#xf5de;</string>
    fa_car_battery_solid,//&#xf5df;</string>
    fa_car_crash_solid,//&#xf5e1;</string>
    fa_car_side_solid,//&#xf5e4;</string>
    fa_charging_station_solid,//&#xf5e7;</string>
    fa_directions_solid,//&#xf5eb;</string>
    fa_draw_polygon_solid,//&#xf5ee;</string>
    fa_laptop_code_solid,//&#xf5fc;</string>
    fa_layer_group_solid,//&#xf5fd;</string>
    fa_microscope_solid,//&#xf610;</string>
    fa_oil_can_solid,//&#xf613;</string>
    fa_poop_solid,//&#xf619;</string>
    fa_shapes_solid,//&#xf61f;</string>
    fa_star_of_life_solid,//&#xf621;</string>
    fa_teeth_solid,//&#xf62e;</string>
    fa_teeth_open_solid,//&#xf62f;</string>
    fa_theater_masks_solid,//&#xf630;</string>
    fa_traffic_light_solid,//&#xf637;</string>
    fa_truck_monster_solid,//&#xf63b;</string>
    fa_truck_pickup_solid,//&#xf63c;</string>
    fa_ad_solid,//&#xf641;</string>
    fa_ankh_solid,//&#xf644;</string>
    fa_bible_solid,//&#xf647;</string>
    fa_business_time_solid,//&#xf64a;</string>
    fa_city_solid,//&#xf64f;</string>
    fa_comment_dollar_solid,//&#xf651;</string>
    fa_comments_dollar_solid,//&#xf653;</string>
    fa_cross_solid,//&#xf654;</string>
    fa_dharmachakra_solid,//&#xf655;</string>
    fa_envelope_open_text_solid,//&#xf658;</string>
    fa_folder_minus_solid,//&#xf65d;</string>
    fa_folder_plus_solid,//&#xf65e;</string>
    fa_funnel_dollar_solid,//&#xf662;</string>
    fa_gopuram_solid,//&#xf664;</string>
    fa_hamsa_solid,//&#xf665;</string>
    fa_haykal_solid,//&#xf666;</string>
    fa_jedi_solid,//&#xf669;</string>
    fa_journal_whills_solid,//&#xf66a;</string>
    fa_kaaba_solid,//&#xf66b;</string>
    fa_khanda_solid,//&#xf66d;</string>
    fa_landmark_solid,//&#xf66f;</string>
    fa_mail_bulk_solid,//&#xf674;</string>
    fa_menorah_solid,//&#xf676;</string>
    fa_mosque_solid,//&#xf678;</string>
    fa_om_solid,//&#xf679;</string>
    fa_pastafarianism_solid,//&#xf67b;</string>
    fa_peace_solid,//&#xf67c;</string>
    fa_place_of_worship_solid,//&#xf67f;</string>
    fa_poll_solid,//&#xf681;</string>
    fa_poll_h_solid,//&#xf682;</string>
    fa_pray_solid,//&#xf683;</string>
    fa_praying_hands_solid,//&#xf684;</string>
    fa_quran_solid,//&#xf687;</string>
    fa_search_dollar_solid,//&#xf688;</string>
    fa_search_location_solid,//&#xf689;</string>
    fa_socks_solid,//&#xf696;</string>
    fa_square_root_alt_solid,//&#xf698;</string>
    fa_star_and_crescent_solid,//&#xf699;</string>
    fa_star_of_david_solid,//&#xf69a;</string>
    fa_synagogue_solid,//&#xf69b;</string>
    fa_torah_solid,//&#xf6a0;</string>
    fa_torii_gate_solid,//&#xf6a1;</string>
    fa_vihara_solid,//&#xf6a7;</string>
    fa_volume_mute_solid,//&#xf6a9;</string>
    fa_yin_yang_solid,//&#xf6ad;</string>
    fa_blender_phone_solid,//&#xf6b6;</string>
    fa_book_dead_solid,//&#xf6b7;</string>
    fa_campground_solid,//&#xf6bb;</string>
    fa_cat_solid,//&#xf6be;</string>
    fa_chair_solid,//&#xf6c0;</string>
    fa_cloud_moon_solid,//&#xf6c3;</string>
    fa_cloud_sun_solid,//&#xf6c4;</string>
    fa_dice_d20_solid,//&#xf6cf;</string>
    fa_dice_d6_solid,//&#xf6d1;</string>
    fa_dog_solid,//&#xf6d3;</string>
    fa_dragon_solid,//&#xf6d5;</string>
    fa_drumstick_bite_solid,//&#xf6d7;</string>
    fa_dungeon_solid,//&#xf6d9;</string>
    fa_file_csv_solid,//&#xf6dd;</string>
    fa_fist_raised_solid,//&#xf6de;</string>
    fa_ghost_solid,//&#xf6e2;</string>
    fa_hammer_solid,//&#xf6e3;</string>
    fa_hanukiah_solid,//&#xf6e6;</string>
    fa_hat_wizard_solid,//&#xf6e8;</string>
    fa_hiking_solid,//&#xf6ec;</string>
    fa_hippo_solid,//&#xf6ed;</string>
    fa_horse_solid,//&#xf6f0;</string>
    fa_house_damage_solid,//&#xf6f1;</string>
    fa_hryvnia_solid,//&#xf6f2;</string>
    fa_mask_solid,//&#xf6fa;</string>
    fa_mountain_solid,//&#xf6fc;</string>
    fa_network_wired_solid,//&#xf6ff;</string>
    fa_otter_solid,//&#xf700;</string>
    fa_ring_solid,//&#xf70b;</string>
    fa_running_solid,//&#xf70c;</string>
    fa_scroll_solid,//&#xf70e;</string>
    fa_skull_crossbones_solid,//&#xf714;</string>
    fa_slash_solid,//&#xf715;</string>
    fa_spider_solid,//&#xf717;</string>
    fa_toilet_paper_solid,//&#xf71e;</string>
    fa_tractor_solid,//&#xf722;</string>
    fa_user_injured_solid,//&#xf728;</string>
    fa_vr_cardboard_solid,//&#xf729;</string>
    fa_wind_solid,//&#xf72e;</string>
    fa_wine_bottle_solid,//&#xf72f;</string>
    fa_cloud_meatball_solid,//&#xf73b;</string>
    fa_cloud_moon_rain_solid,//&#xf73c;</string>
    fa_cloud_rain_solid,//&#xf73d;</string>
    fa_cloud_showers_heavy_solid,//&#xf740;</string>
    fa_cloud_sun_rain_solid,//&#xf743;</string>
    fa_democrat_solid,//&#xf747;</string>
    fa_flag_usa_solid,//&#xf74d;</string>
    fa_meteor_solid,//&#xf753;</string>
    fa_person_booth_solid,//&#xf756;</string>
    fa_poo_storm_solid,//&#xf75a;</string>
    fa_rainbow_solid,//&#xf75b;</string>
    fa_republican_solid,//&#xf75e;</string>
    fa_smog_solid,//&#xf75f;</string>
    fa_temperature_high_solid,//&#xf769;</string>
    fa_temperature_low_solid,//&#xf76b;</string>
    fa_vote_yea_solid,//&#xf772;</string>
    fa_water_solid,//&#xf773;</string>
    fa_baby_solid,//&#xf77c;</string>
    fa_baby_carriage_solid,//&#xf77d;</string>
    fa_biohazard_solid,//&#xf780;</string>
    fa_blog_solid,//&#xf781;</string>
    fa_calendar_day_solid,//&#xf783;</string>
    fa_calendar_week_solid,//&#xf784;</string>
    fa_candy_cane_solid,//&#xf786;</string>
    fa_carrot_solid,//&#xf787;</string>
    fa_cash_register_solid,//&#xf788;</string>
    fa_compress_arrows_alt_solid,//&#xf78c;</string>
    fa_dumpster_solid,//&#xf793;</string>
    fa_dumpster_fire_solid,//&#xf794;</string>
    fa_ethernet_solid,//&#xf796;</string>
    fa_gifts_solid,//&#xf79c;</string>
    fa_glass_cheers_solid,//&#xf79f;</string>
    fa_glass_whiskey_solid,//&#xf7a0;</string>
    fa_globe_europe_solid,//&#xf7a2;</string>
    fa_grip_lines_solid,//&#xf7a4;</string>
    fa_grip_lines_vertical_solid,//&#xf7a5;</string>
    fa_guitar_solid,//&#xf7a6;</string>
    fa_heart_broken_solid,//&#xf7a9;</string>
    fa_holly_berry_solid,//&#xf7aa;</string>
    fa_horse_head_solid,//&#xf7ab;</string>
    fa_icicles_solid,//&#xf7ad;</string>
    fa_igloo_solid,//&#xf7ae;</string>
    fa_mitten_solid,//&#xf7b5;</string>
    fa_mug_hot_solid,//&#xf7b6;</string>
    fa_radiation_solid,//&#xf7b9;</string>
    fa_radiation_alt_solid,//&#xf7ba;</string>
    fa_restroom_solid,//&#xf7bd;</string>
    fa_satellite_solid,//&#xf7bf;</string>
    fa_satellite_dish_solid,//&#xf7c0;</string>
    fa_sd_card_solid,//&#xf7c2;</string>
    fa_sim_card_solid,//&#xf7c4;</string>
    fa_skating_solid,//&#xf7c5;</string>
    fa_skiing_solid,//&#xf7c9;</string>
    fa_skiing_nordic_solid,//&#xf7ca;</string>
    fa_sleigh_solid,//&#xf7cc;</string>
    fa_sms_solid,//&#xf7cd;</string>
    fa_snowboarding_solid,//&#xf7ce;</string>
    fa_snowman_solid,//&#xf7d0;</string>
    fa_snowplow_solid,//&#xf7d2;</string>
    fa_tenge_solid,//&#xf7d7;</string>
    fa_toilet_solid,//&#xf7d8;</string>
    fa_tools_solid,//&#xf7d9;</string>
    fa_tram_solid,//&#xf7da;</string>
    fa_fire_alt_solid,//&#xf7e4;</string>
    fa_bacon_solid,//&#xf7e5;</string>
    fa_book_medical_solid,//&#xf7e6;</string>
    fa_bread_slice_solid,//&#xf7ec;</string>
    fa_cheese_solid,//&#xf7ef;</string>
    fa_clinic_medical_solid,//&#xf7f2;</string>
    fa_comment_medical_solid,//&#xf7f5;</string>
    fa_crutch_solid,//&#xf7f7;</string>
    fa_egg_solid,//&#xf7fb;</string>
    fa_hamburger_solid,//&#xf805;</string>
    fa_hand_middle_finger_solid,//&#xf806;</string>
    fa_hard_hat_solid,//&#xf807;</string>
    fa_hotdog_solid,//&#xf80f;</string>
    fa_ice_cream_solid,//&#xf810;</string>
    fa_laptop_medical_solid,//&#xf812;</string>
    fa_pager_solid,//&#xf815;</string>
    fa_pepper_hot_solid,//&#xf816;</string>
    fa_pizza_slice_solid,//&#xf818;</string>
    fa_trash_restore_solid,//&#xf829;</string>
    fa_trash_restore_alt_solid,//&#xf82a;</string>
    fa_user_nurse_solid,//&#xf82f;</string>


    fa_twitter_square,//&#xf081;</string>
    fa_facebook_square,//&#xf082;</string>
    fa_linkedin,//&#xf08c;</string>
    fa_github_square,//&#xf092;</string>
    fa_twitter,//&#xf099;</string>
    fa_facebook,//&#xf09a;</string>
    fa_github,//&#xf09b;</string>
    fa_pinterest,//&#xf0d2;</string>
    fa_pinterest_square,//&#xf0d3;</string>
    fa_google_plus_square,//&#xf0d4;</string>
    fa_google_plus_g,//&#xf0d5;</string>
    fa_linkedin_in,//&#xf0e1;</string>
    fa_github_alt,//&#xf113;</string>
    fa_maxcdn,//&#xf136;</string>
    fa_html5,//&#xf13b;</string>
    fa_css3,//&#xf13c;</string>
    fa_btc,//&#xf15a;</string>
    fa_youtube,//&#xf167;</string>
    fa_xing,//&#xf168;</string>
    fa_xing_square,//&#xf169;</string>
    fa_dropbox,//&#xf16b;</string>
    fa_stack_overflow,//&#xf16c;</string>
    fa_instagram,//&#xf16d;</string>
    fa_flickr,//&#xf16e;</string>
    fa_adn,//&#xf170;</string>
    fa_bitbucket,//&#xf171;</string>
    fa_tumblr,//&#xf173;</string>
    fa_tumblr_square,//&#xf174;</string>
    fa_apple,//&#xf179;</string>
    fa_windows,//&#xf17a;</string>
    fa_android,//&#xf17b;</string>
    fa_linux,//&#xf17c;</string>
    fa_dribbble,//&#xf17d;</string>
    fa_skype,//&#xf17e;</string>
    fa_foursquare,//&#xf180;</string>
    fa_trello,//&#xf181;</string>
    fa_gratipay,//&#xf184;</string>
    fa_vk,//&#xf189;</string>
    fa_weibo,//&#xf18a;</string>
    fa_renren,//&#xf18b;</string>
    fa_pagelines,//&#xf18c;</string>
    fa_stack_exchange,//&#xf18d;</string>
    fa_vimeo_square,//&#xf194;</string>
    fa_slack,//&#xf198;</string>
    fa_wordpress,//&#xf19a;</string>
    fa_openid,//&#xf19b;</string>
    fa_yahoo,//&#xf19e;</string>
    fa_google,//&#xf1a0;</string>
    fa_reddit,//&#xf1a1;</string>
    fa_reddit_square,//&#xf1a2;</string>
    fa_stumbleupon_circle,//&#xf1a3;</string>
    fa_stumbleupon,//&#xf1a4;</string>
    fa_delicious,//&#xf1a5;</string>
    fa_digg,//&#xf1a6;</string>
    fa_pied_piper_pp,//&#xf1a7;</string>
    fa_pied_piper_alt,//&#xf1a8;</string>
    fa_drupal,//&#xf1a9;</string>
    fa_joomla,//&#xf1aa;</string>
    fa_behance,//&#xf1b4;</string>
    fa_behance_square,//&#xf1b5;</string>
    fa_steam,//&#xf1b6;</string>
    fa_steam_square,//&#xf1b7;</string>
    fa_spotify,//&#xf1bc;</string>
    fa_deviantart,//&#xf1bd;</string>
    fa_soundcloud,//&#xf1be;</string>
    fa_vine,//&#xf1ca;</string>
    fa_codepen,//&#xf1cb;</string>
    fa_jsfiddle,//&#xf1cc;</string>
    fa_rebel,//&#xf1d0;</string>
    fa_empire,//&#xf1d1;</string>
    fa_git_square,//&#xf1d2;</string>
    fa_git,//&#xf1d3;</string>
    fa_hacker_news,//&#xf1d4;</string>
    fa_tencent_weibo,//&#xf1d5;</string>
    fa_qq,//&#xf1d6;</string>
    fa_weixin,//&#xf1d7;</string>
    fa_slideshare,//&#xf1e7;</string>
    fa_twitch,//&#xf1e8;</string>
    fa_yelp,//&#xf1e9;</string>
    fa_paypal,//&#xf1ed;</string>
    fa_google_wallet,//&#xf1ee;</string>
    fa_cc_visa,//&#xf1f0;</string>
    fa_cc_mastercard,//&#xf1f1;</string>
    fa_cc_discover,//&#xf1f2;</string>
    fa_cc_amex,//&#xf1f3;</string>
    fa_cc_paypal,//&#xf1f4;</string>
    fa_cc_stripe,//&#xf1f5;</string>
    fa_lastfm,//&#xf202;</string>
    fa_lastfm_square,//&#xf203;</string>
    fa_ioxhost,//&#xf208;</string>
    fa_angellist,//&#xf209;</string>
    fa_buysellads,//&#xf20d;</string>
    fa_connectdevelop,//&#xf20e;</string>
    fa_dashcube,//&#xf210;</string>
    fa_forumbee,//&#xf211;</string>
    fa_leanpub,//&#xf212;</string>
    fa_sellsy,//&#xf213;</string>
    fa_shirtsinbulk,//&#xf214;</string>
    fa_simplybuilt,//&#xf215;</string>
    fa_skyatlas,//&#xf216;</string>
    fa_pinterest_p,//&#xf231;</string>
    fa_whatsapp,//&#xf232;</string>
    fa_viacoin,//&#xf237;</string>
    fa_medium,//&#xf23a;</string>
    fa_y_combinator,//&#xf23b;</string>
    fa_optin_monster,//&#xf23c;</string>
    fa_opencart,//&#xf23d;</string>
    fa_expeditedssl,//&#xf23e;</string>
    fa_cc_jcb,//&#xf24b;</string>
    fa_cc_diners_club,//&#xf24c;</string>
    fa_creative_commons,//&#xf25e;</string>
    fa_gg,//&#xf260;</string>
    fa_gg_circle,//&#xf261;</string>
    fa_tripadvisor,//&#xf262;</string>
    fa_odnoklassniki,//&#xf263;</string>
    fa_odnoklassniki_square,//&#xf264;</string>
    fa_get_pocket,//&#xf265;</string>
    fa_wikipedia_w,//&#xf266;</string>
    fa_safari,//&#xf267;</string>
    fa_chrome,//&#xf268;</string>
    fa_firefox,//&#xf269;</string>
    fa_opera,//&#xf26a;</string>
    fa_internet_explorer,//&#xf26b;</string>
    fa_contao,//&#xf26d;</string>
    fa_500px,//&#xf26e;</string>
    fa_amazon,//&#xf270;</string>
    fa_houzz,//&#xf27c;</string>
    fa_vimeo_v,//&#xf27d;</string>
    fa_black_tie,//&#xf27e;</string>
    fa_fonticons,//&#xf280;</string>
    fa_reddit_alien,//&#xf281;</string>
    fa_edge,//&#xf282;</string>
    fa_codiepie,//&#xf284;</string>
    fa_modx,//&#xf285;</string>
    fa_fort_awesome,//&#xf286;</string>
    fa_usb,//&#xf287;</string>
    fa_product_hunt,//&#xf288;</string>
    fa_mixcloud,//&#xf289;</string>
    fa_scribd,//&#xf28a;</string>
    fa_bluetooth,//&#xf293;</string>
    fa_bluetooth_b,//&#xf294;</string>
    fa_gitlab,//&#xf296;</string>
    fa_wpbeginner,//&#xf297;</string>
    fa_wpforms,//&#xf298;</string>
    fa_envira,//&#xf299;</string>
    fa_glide,//&#xf2a5;</string>
    fa_glide_g,//&#xf2a6;</string>
    fa_viadeo,//&#xf2a9;</string>
    fa_viadeo_square,//&#xf2aa;</string>
    fa_snapchat,//&#xf2ab;</string>
    fa_snapchat_ghost,//&#xf2ac;</string>
    fa_snapchat_square,//&#xf2ad;</string>
    fa_pied_piper,//&#xf2ae;</string>
    fa_first_order,//&#xf2b0;</string>
    fa_yoast,//&#xf2b1;</string>
    fa_themeisle,//&#xf2b2;</string>
    fa_google_plus,//&#xf2b3;</string>
    fa_font_awesome,//&#xf2b4;</string>
    fa_linode,//&#xf2b8;</string>
    fa_quora,//&#xf2c4;</string>
    fa_free_code_camp,//&#xf2c5;</string>
    fa_telegram,//&#xf2c6;</string>
    fa_bandcamp,//&#xf2d5;</string>
    fa_grav,//&#xf2d6;</string>
    fa_etsy,//&#xf2d7;</string>
    fa_imdb,//&#xf2d8;</string>
    fa_ravelry,//&#xf2d9;</string>
    fa_sellcast,//&#xf2da;</string>
    fa_superpowers,//&#xf2dd;</string>
    fa_wpexplorer,//&#xf2de;</string>
    fa_meetup,//&#xf2e0;</string>
    fa_font_awesome_alt,//&#xf35c;</string>
    fa_accessible_icon,//&#xf368;</string>
    fa_accusoft,//&#xf369;</string>
    fa_adversal,//&#xf36a;</string>
    fa_affiliatetheme,//&#xf36b;</string>
    fa_algolia,//&#xf36c;</string>
    fa_amilia,//&#xf36d;</string>
    fa_angrycreative,//&#xf36e;</string>
    fa_app_store,//&#xf36f;</string>
    fa_app_store_ios,//&#xf370;</string>
    fa_apper,//&#xf371;</string>
    fa_asymmetrik,//&#xf372;</string>
    fa_audible,//&#xf373;</string>
    fa_avianex,//&#xf374;</string>
    fa_aws,//&#xf375;</string>
    fa_bimobject,//&#xf378;</string>
    fa_bitcoin,//&#xf379;</string>
    fa_bity,//&#xf37a;</string>
    fa_blackberry,//&#xf37b;</string>
    fa_blogger,//&#xf37c;</string>
    fa_blogger_b,//&#xf37d;</string>
    fa_buromobelexperte,//&#xf37f;</string>
    fa_centercode,//&#xf380;</string>
    fa_cloudscale,//&#xf383;</string>
    fa_cloudsmith,//&#xf384;</string>
    fa_cloudversify,//&#xf385;</string>
    fa_cpanel,//&#xf388;</string>
    fa_css3_alt,//&#xf38b;</string>
    fa_cuttlefish,//&#xf38c;</string>
    fa_d_and_d,//&#xf38d;</string>
    fa_deploydog,//&#xf38e;</string>
    fa_deskpro,//&#xf38f;</string>
    fa_digital_ocean,//&#xf391;</string>
    fa_discord,//&#xf392;</string>
    fa_discourse,//&#xf393;</string>
    fa_dochub,//&#xf394;</string>
    fa_docker,//&#xf395;</string>
    fa_draft2digital,//&#xf396;</string>
    fa_dribbble_square,//&#xf397;</string>
    fa_dyalog,//&#xf399;</string>
    fa_earlybirds,//&#xf39a;</string>
    fa_erlang,//&#xf39d;</string>
    fa_facebook_f,//&#xf39e;</string>
    fa_facebook_messenger,//&#xf39f;</string>
    fa_firstdraft,//&#xf3a1;</string>
    fa_fonticons_fi,//&#xf3a2;</string>
    fa_fort_awesome_alt,//&#xf3a3;</string>
    fa_freebsd,//&#xf3a4;</string>
    fa_gitkraken,//&#xf3a6;</string>
    fa_gofore,//&#xf3a7;</string>
    fa_goodreads,//&#xf3a8;</string>
    fa_goodreads_g,//&#xf3a9;</string>
    fa_google_drive,//&#xf3aa;</string>
    fa_google_play,//&#xf3ab;</string>
    fa_gripfire,//&#xf3ac;</string>
    fa_grunt,//&#xf3ad;</string>
    fa_gulp,//&#xf3ae;</string>
    fa_hacker_news_square,//&#xf3af;</string>
    fa_hire_a_helper,//&#xf3b0;</string>
    fa_hotjar,//&#xf3b1;</string>
    fa_hubspot,//&#xf3b2;</string>
    fa_itunes,//&#xf3b4;</string>
    fa_itunes_note,//&#xf3b5;</string>
    fa_jenkins,//&#xf3b6;</string>
    fa_joget,//&#xf3b7;</string>
    fa_js,//&#xf3b8;</string>
    fa_js_square,//&#xf3b9;</string>
    fa_keycdn,//&#xf3ba;</string>
    fa_kickstarter,//&#xf3bb;</string>
    fa_kickstarter_k,//&#xf3bc;</string>
    fa_laravel,//&#xf3bd;</string>
    fa_line,//&#xf3c0;</string>
    fa_lyft,//&#xf3c3;</string>
    fa_magento,//&#xf3c4;</string>
    fa_medapps,//&#xf3c6;</string>
    fa_medium_m,//&#xf3c7;</string>
    fa_medrt,//&#xf3c8;</string>
    fa_microsoft,//&#xf3ca;</string>
    fa_mix,//&#xf3cb;</string>
    fa_mizuni,//&#xf3cc;</string>
    fa_monero,//&#xf3d0;</string>
    fa_napster,//&#xf3d2;</string>
    fa_node_js,//&#xf3d3;</string>
    fa_npm,//&#xf3d4;</string>
    fa_ns8,//&#xf3d5;</string>
    fa_nutritionix,//&#xf3d6;</string>
    fa_page4,//&#xf3d7;</string>
    fa_palfed,//&#xf3d8;</string>
    fa_patreon,//&#xf3d9;</string>
    fa_periscope,//&#xf3da;</string>
    fa_phabricator,//&#xf3db;</string>
    fa_phoenix_framework,//&#xf3dc;</string>
    fa_playstation,//&#xf3df;</string>
    fa_pushed,//&#xf3e1;</string>
    fa_python,//&#xf3e2;</string>
    fa_red_river,//&#xf3e3;</string>
    fa_wpressr,//&#xf3e4;</string>
    fa_replyd,//&#xf3e6;</string>
    fa_resolving,//&#xf3e7;</string>
    fa_rocketchat,//&#xf3e8;</string>
    fa_rockrms,//&#xf3e9;</string>
    fa_schlix,//&#xf3ea;</string>
    fa_searchengin,//&#xf3eb;</string>
    fa_servicestack,//&#xf3ec;</string>
    fa_sistrix,//&#xf3ee;</string>
    fa_slack_hash,//&#xf3ef;</string>
    fa_speakap,//&#xf3f3;</string>
    fa_staylinked,//&#xf3f5;</string>
    fa_steam_symbol,//&#xf3f6;</string>
    fa_sticker_mule,//&#xf3f7;</string>
    fa_studiovinari,//&#xf3f8;</string>
    fa_supple,//&#xf3f9;</string>
    fa_telegram_plane,//&#xf3fe;</string>
    fa_uber,//&#xf402;</string>
    fa_uikit,//&#xf403;</string>
    fa_uniregistry,//&#xf404;</string>
    fa_untappd,//&#xf405;</string>
    fa_ussunnah,//&#xf407;</string>
    fa_vaadin,//&#xf408;</string>
    fa_viber,//&#xf409;</string>
    fa_vimeo,//&#xf40a;</string>
    fa_vnv,//&#xf40b;</string>
    fa_whatsapp_square,//&#xf40c;</string>
    fa_whmcs,//&#xf40d;</string>
    fa_wordpress_simple,//&#xf411;</string>
    fa_xbox,//&#xf412;</string>
    fa_yandex,//&#xf413;</string>
    fa_yandex_international,//&#xf414;</string>
    fa_apple_pay,//&#xf415;</string>
    fa_cc_apple_pay,//&#xf416;</string>
    fa_fly,//&#xf417;</string>
    fa_nintendo_switch,//&#xf418;</string>
    fa_node,//&#xf419;</string>
    fa_osi,//&#xf41a;</string>
    fa_react,//&#xf41b;</string>
    fa_autoprefixer,//&#xf41c;</string>
    fa_less,//&#xf41d;</string>
    fa_sass,//&#xf41e;</string>
    fa_vuejs,//&#xf41f;</string>
    fa_angular,//&#xf420;</string>
    fa_aviato,//&#xf421;</string>
    fa_ember,//&#xf423;</string>
    fa_font_awesome_flag,//&#xf425;</string>
    fa_gitter,//&#xf426;</string>
    fa_hooli,//&#xf427;</string>
    fa_strava,//&#xf428;</string>
    fa_stripe,//&#xf429;</string>
    fa_stripe_s,//&#xf42a;</string>
    fa_typo3,//&#xf42b;</string>
    fa_amazon_pay,//&#xf42c;</string>
    fa_cc_amazon_pay,//&#xf42d;</string>
    fa_ethereum,//&#xf42e;</string>
    fa_korvue,//&#xf42f;</string>
    fa_elementor,//&#xf430;</string>
    fa_youtube_square,//&#xf431;</string>
    fa_flipboard,//&#xf44d;</string>
    fa_hips,//&#xf452;</string>
    fa_php,//&#xf457;</string>
    fa_quinscape,//&#xf459;</string>
    fa_readme,//&#xf4d5;</string>
    fa_java,//&#xf4e4;</string>
    fa_pied_piper_hat,//&#xf4e5;</string>
    fa_creative_commons_by,//&#xf4e7;</string>
    fa_creative_commons_nc,//&#xf4e8;</string>
    fa_creative_commons_nc_eu,//&#xf4e9;</string>
    fa_creative_commons_nc_jp,//&#xf4ea;</string>
    fa_creative_commons_nd,//&#xf4eb;</string>
    fa_creative_commons_pd,//&#xf4ec;</string>
    fa_creative_commons_pd_alt,//&#xf4ed;</string>
    fa_creative_commons_remix,//&#xf4ee;</string>
    fa_creative_commons_sa,//&#xf4ef;</string>
    fa_creative_commons_sampling,//&#xf4f0;</string>
    fa_creative_commons_sampling_plus,//&#xf4f1;</string>
    fa_creative_commons_share,//&#xf4f2;</string>
    fa_creative_commons_zero,//&#xf4f3;</string>
    fa_ebay,//&#xf4f4;</string>
    fa_keybase,//&#xf4f5;</string>
    fa_mastodon,//&#xf4f6;</string>
    fa_r_project,//&#xf4f7;</string>
    fa_researchgate,//&#xf4f8;</string>
    fa_teamspeak,//&#xf4f9;</string>
    fa_first_order_alt,//&#xf50a;</string>
    fa_fulcrum,//&#xf50b;</string>
    fa_galactic_republic,//&#xf50c;</string>
    fa_galactic_senate,//&#xf50d;</string>
    fa_jedi_order,//&#xf50e;</string>
    fa_mandalorian,//&#xf50f;</string>
    fa_old_republic,//&#xf510;</string>
    fa_phoenix_squadron,//&#xf511;</string>
    fa_sith,//&#xf512;</string>
    fa_trade_federation,//&#xf513;</string>
    fa_wolf_pack_battalion,//&#xf514;</string>
    fa_hornbill,//&#xf592;</string>
    fa_mailchimp,//&#xf59e;</string>
    fa_megaport,//&#xf5a3;</string>
    fa_nimblr,//&#xf5a8;</string>
    fa_rev,//&#xf5b2;</string>
    fa_shopware,//&#xf5b5;</string>
    fa_squarespace,//&#xf5be;</string>
    fa_themeco,//&#xf5c6;</string>
    fa_weebly,//&#xf5cc;</string>
    fa_wix,//&#xf5cf;</string>
    fa_ello,//&#xf5f1;</string>
    fa_hackerrank,//&#xf5f7;</string>
    fa_kaggle,//&#xf5fa;</string>
    fa_markdown,//&#xf60f;</string>
    fa_neos,//&#xf612;</string>
    fa_zhihu,//&#xf63f;</string>
    fa_alipay,//&#xf642;</string>
    fa_the_red_yeti,//&#xf69d;</string>
    fa_acquisitions_incorporated,//&#xf6af;</string>
    fa_critical_role,//&#xf6c9;</string>
    fa_d_and_d_beyond,//&#xf6ca;</string>
    fa_dev,//&#xf6cc;</string>
    fa_fantasy_flight_games,//&#xf6dc;</string>
    fa_penny_arcade,//&#xf704;</string>
    fa_wizards_of_the_coast,//&#xf730;</string>
    fa_think_peaks,//&#xf731;</string>
    fa_reacteurope,//&#xf75d;</string>
    fa_adobe,//&#xf778;</string>
    fa_artstation,//&#xf77a;</string>
    fa_atlassian,//&#xf77b;</string>
    fa_canadian_maple_leaf,//&#xf785;</string>
    fa_centos,//&#xf789;</string>
    fa_confluence,//&#xf78d;</string>
    fa_dhl,//&#xf790;</string>
    fa_diaspora,//&#xf791;</string>
    fa_fedex,//&#xf797;</string>
    fa_fedora,//&#xf798;</string>
    fa_figma,//&#xf799;</string>
    fa_intercom,//&#xf7af;</string>
    fa_invision,//&#xf7b0;</string>
    fa_jira,//&#xf7b1;</string>
    fa_mendeley,//&#xf7b3;</string>
    fa_raspberry_pi,//&#xf7bb;</string>
    fa_redhat,//&#xf7bc;</string>
    fa_sketch,//&#xf7c6;</string>
    fa_sourcetree,//&#xf7d3;</string>
    fa_suse,//&#xf7d6;</string>
    fa_ubuntu,//&#xf7df;</string>
    fa_ups,//&#xf7e0;</string>
    fa_usps,//&#xf7e1;</string>
    fa_yarn,//&#xf7e3;</string>



}
